### PR TITLE
replace file by environment variables #9

### PR DESCRIPTION
**Pull request by themousepotato**
[ce35c12](https://github.com/metakgp/Zoom/commit/ce35c12d5c1e04d44174ddd2231a43142e0c5e35) and [79ae3b8](https://github.com/metakgp/Zoom/commit/79ae3b84a372f733dd2ff7464e834b90b103ef91) also changed.

### CODE REVIEW

**Comment by ghostwriternr** [comment]
The changes look good to me, but it'd be nice if someone could test it as well.

**Comment by icyflame** [comment]
This looks fine. But aren't there more variables? I don't think this is the only one that needs to be put in the env.

**Review by icyflame — APPROVED** [review]

**Comment by themousepotato** [comment]
@icyflame three files changed. i.e [ce35c12](https://github.com/metakgp/Zoom/commit/ce35c12d5c1e04d44174ddd2231a43142e0c5e35) and [79ae3b8](https://github.com/metakgp/Zoom/commit/79ae3b84a372f733dd2ff7464e834b90b103ef91) also.

**Comment by icyflame** [comment]
Those changes are not visible in this PR. You have to make the commits on a branch and then open a pull request. Have a look at [this guide](https://help.github.com/articles/creating-a-pull-request/) and **check** your pull request _before_ creating it.

**Comment by themousepotato** [comment]
@ghostwriternr I merged those branches and deleted the old ones. But, merge conflicts are occurring. Help, please!

**Comment by themousepotato** [comment]
@icyflame Resolved merge conflicts. Ready to merge.

**Pull request merged**
