### PR TITLE
Add license

### PR DESCRIPTION
**Pull request by themousepotato**

### CODE REVIEW

**Comment by ghostwriternr** [comment]
Hey @TheMousePotato ,

Thanks for your PRs. I'm not super sure about the config required for testing your changes. I'm hoping @DefCon-007  will get to it soon. But ideally, try to keep your commit history as clean as possible. There's a lot of commits here in this PR that could have been made in one. You don't have to worry about it now as we can do a 'squash and merge' in this case. But for slightly less trivial PRs, it would be much nicer if each commit contained self-contained meaningful and non-redundant changes.

In future, if it ever comes to having a messy commit history (which might happen sometimes for good reason as well), you can have a look at git's interactive rebase. It's super easy to use and really useful!
https://christoph-rumpel.com/2015/05/clean-up-your-commits-for-a-pull-request/

Also, I highly recommend reading [this blog post](https://chris.beams.io/posts/git-commit/) on writing good commit messages. It's a very simple and well-written guide that you can follow in the future! :wink:

**Review by ghostwriternr — APPROVED** [review]
Hey! Thanks a ton for your PR. GPLv3 seems like an okay choice for this project. We use GPLv3 for most of our projects.

In future if you ever see yourself creating a new project and are confused about which license to pick, have a look at the open source license descriptions online to see if your license is compatible with the other software/libraries you use. For instance, facepy uses MIT license, which is 'permissive' and is compatible with GPLv3 (which is more 'restrictive' than MIT). So it's okay to use. I'm no expert at this topic though, so @hargup is the person to contact if you ever face a dead end in a future scenario.

Cheers!

**Comment by themousepotato** [comment]
Thanks @ghostwriternr

**Comment by icyflame** [comment]
I don't have _very strong feelings_ about this, but it might be great if we could just agree on using MIT for all Metakgp projects? It's permissive and we don't buy into the whole BSD v. GPL war. Just putting this out there. This has already been discussed on issues in other projects, I think.

**Comment by hargup** [comment]
> It's permissive and we don't buy into the whole BSD v. GPL war. Just putting this out there. This has already been discussed on issues in other projects, I think.

I would say if you don't care about BSD v. GPL, use GPL because this gives us a bigger base of projects to work on. With BSD software, you can only build upon BSD software, but with GPL you can build upon both BSD and GPL. Also, many of our projects like MFTP and Naarad are GPL, better use GPL so that you also integrate with them.

**Comment by icyflame** [comment]
Oh, great. So, GPL ensures we can use whatever. Yeah, then this choice doesn't matter at all. Thanks for clarifying! :+1: 

Another doubt: I can re-license BSD software using MIT right? i.e if this project is licensed under MIT, I can use any software that was licensed under BSD or GPL in here?

**Comment by DefCon-007** [comment]
@hargup @icyflame Should we merge this ?

**Comment by hargup** [comment]
Fine with me.

**Comment by ghostwriternr** [comment]
Thanks again, @TheMousePotato !

**Pull request merged**
